### PR TITLE
Fix "ship test" and web UI (#3, #4)

### LINKED ISSUE #3: ship test fails with NullPointerException and no other details
I cloned https://github.com/aergoio/athena-370/ and got this error:

```
$ ship install aergoio/athena-343
Successful to install aergoio/athena-343.
Install path: /home/adam/.aergo_modules/aergoio/athena-343

$ ship test                      
 o src/test/lua/test-util.lua
nested exception is java.lang.NullPointerException
Unexpected exception!! Report the bug to support@aergo.io
```

I reported the bug to the email address, but I thought it would be worth reporting here too.  I think `ship` should show the details of the exception (e.g. stacktrace) so that we can debug it more easily.

### LINKED ISSUE #4: can't launch ship web UI
I wanted to try ship's web UI, but this happened:

```
$ ship build --watch --port 8080
 ERROR  No auto configuration classes found in META-INF/spring.factories. If you are using a custom packaging, make sure that file is correct.
```

### PR DESCRIPTION
**Pull request by aspiers**
Fix regressions to ship test and the web UI caused by the wrong class path.

Also, if for some reason discovery of the lua script engine fails, die with a more helpful error message than a `NullPointerException`.

Fixes #3 and fixes #4.

### CODE REVIEW

**Comment by aspiers** [comment]
I have just realised that this bug was caused by f2ae27587fef58e4562, which prevents the correct jars from getting onto the classpath.

**Comment by aspiers** [comment]
Thanks @ashen1dev.

@acktsap I can't see an easy way to test the new code path (when the lookup for the lua script engine returns `null`) because that would require dynamically changing classpath within `LuaRunnerTest.java`, and AFAIK that would require some complicated tricks with a custom `ClassLoader`.

So unfortunately this PR slightly reduces code coverage, but it's only a tiny bit.  If you have any ideas how to get around this, please let me know!

**Comment by acktsap** [comment]
As you can see in https://github.com/aergoio/ship/tree/develop/bootstrap

**Comment by acktsap** [comment]
Directly passing jar files has been replaced with custom class loader (see bootstrap module). As you can see in https://github.com/aergoio/ship/tree/develop/bootstrap, bootstrap module loads required classpathes. It seems we have to fix that module. Not directly loading jar files.

**Comment by acktsap** [comment]
Thanks for reporting. Slight changes of coverage isn't matter.
I changed custom classloader to load resources correctly. See f74385e0a53b98eda0926c766c6ab5f0228aad62.

It seems `ship test` and `ship build --watch --port 8080` works. Close the issue.

**Pull request merged**
